services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./sbir_transitions.db
