services:
  sbir-classifier:
    build: .
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - DATABASE_URL=sqlite:///./data/sbir_transitions.db
    stdin_open: true
    tty: true
