$schema: "http://json-schema.org/draft-07/schema#"
title: SBIR Transition Classifier Configuration
description: Schema for YAML configuration files
type: object

properties:
  schema_version:
    type: string
    description: Configuration schema version
    enum: ["1.0"]
    
  detection:
    type: object
    description: Detection algorithm parameters
    properties:
      thresholds:
        type: object
        description: Score thresholds for classification
        properties:
          high_confidence:
            type: number
            minimum: 0.0
            maximum: 1.0
            description: Minimum score for high-confidence detection
            default: 0.85
          likely_transition:
            type: number
            minimum: 0.0
            maximum: 1.0
            description: Minimum score for likely transition detection
            default: 0.65
        required: [high_confidence, likely_transition]
        additionalProperties: false
        
      weights:
        type: object
        description: Feature weights for scoring
        properties:
          sole_source_bonus:
            type: number
            minimum: 0.0
            description: Additional weight for sole-source contracts
            default: 0.2
          timing_weight:
            type: number
            minimum: 0.0
            description: Weight for timing proximity to Phase II completion
            default: 0.15
          agency_continuity:
            type: number
            minimum: 0.0
            description: Weight for same agency/service continuation
            default: 0.25
          text_similarity:
            type: number
            minimum: 0.0
            description: Weight for description text similarity
            default: 0.1
        required: [sole_source_bonus, timing_weight, agency_continuity, text_similarity]
        additionalProperties: false
        
      features:
        type: object
        description: Feature toggle flags
        properties:
          enable_cross_service:
            type: boolean
            description: Include cross-service transitions in detection
            default: true
          enable_text_analysis:
            type: boolean
            description: Use text similarity analysis
            default: false
          enable_competed_contracts:
            type: boolean
            description: Include competed contracts in detection
            default: true
        required: [enable_cross_service, enable_text_analysis, enable_competed_contracts]
        additionalProperties: false
        
      timing:
        type: object
        description: Timing constraints for detection
        properties:
          max_months_after_phase2:
            type: integer
            minimum: 1
            maximum: 60
            description: Maximum months after Phase II completion to search
            default: 24
          min_months_after_phase2:
            type: integer
            minimum: 0
            maximum: 12
            description: Minimum months after Phase II completion to search
            default: 0
        required: [max_months_after_phase2, min_months_after_phase2]
        additionalProperties: false
        
    required: [thresholds, weights, features, timing]
    additionalProperties: false
    
  output:
    type: object
    description: Output format and content configuration
    properties:
      formats:
        type: array
        items:
          type: string
          enum: ["jsonl", "csv", "excel"]
        description: Output file formats to generate
        default: ["jsonl", "csv"]
        minItems: 1
      include_evidence:
        type: boolean
        description: Include detailed evidence bundles
        default: true
      evidence_detail_level:
        type: string
        enum: ["summary", "full"]
        description: Level of detail in evidence bundles
        default: "full"
    required: [formats, include_evidence, evidence_detail_level]
    additionalProperties: false

required: [schema_version, detection, output]
additionalProperties: false

# Validation rules that cannot be expressed in JSON Schema
custom_validations:
  - name: threshold_ordering
    description: "likely_transition threshold must be <= high_confidence threshold"
    rule: "detection.thresholds.likely_transition <= detection.thresholds.high_confidence"
  - name: timing_ordering  
    description: "min_months_after_phase2 must be < max_months_after_phase2"
    rule: "detection.timing.min_months_after_phase2 < detection.timing.max_months_after_phase2"
